### ISSUE TITLE
Restore the original freelens-node-pod-menu publish workflow

### ISSUE THREAD

**Issue by robertobandini** [freelensapp/freelens-node-pod-menu#32]
Our brand new npm token is already configured in this repo.
So we can restore the original publish workflow:
https://github.com/alebcay/openlens-node-pod-menu/blob/main/.github/workflows/publish.yaml
We can do this eventually after we finished to recreate a release workflow about Freelens, let's see:
https://github.com/freelensapp/freelens/issues/10

@dex4er fyi

**Comment by dex4er** [comment]
#33 restored publishing to NPM

**Comment by robertobandini** [comment]
Perfect! Thank you very much!
